name: Build L2Protection DLL

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: |
        msbuild dsetup.sln /p:Configuration=Release /p:Platform=x86

    - name: Upload Compiled DLL
      uses: actions/upload-artifact@v4
      with:
        name: dsetup-dll
        path: dist/dsetup.dll
        
